---
- name: Create Database from file
  become: true
  mysql_db:
    state: import
    name: '{{dbname}}'
    login_unix_socket: /var/run/mysqld/mysqld.sock
    target: /srv/code/{{dbname}}.sql

- name: Create Database User
  become: true
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: '{{dbuser}}'
    password: '{{dbpwd}}'
    priv: '{{dbname}}.*:ALL'
    state: present


#- name: Create Database.
#  become: true
#  mysql_db: >
#    name={{dbuser}}
#    owner={{dbpwd}}
#    login_host=localhost
#    login_user={{dbuser}}
#    login_password={{dbpwd}}
#  tags:
#    - database
#    - create
