---
- hosts: all
  vars:
    - dbuser: 'min_db_user'
    - dbpwd: 'passwordyall'
    - dbname: 'mineralDB'

  tasks:
    - include: packages.yml
    - include: mysql.yml
    - include: pip.yml
    - include: nginx.yml
    - include: activate.yml
