---
- hosts: all
  vars:
  - dbuser: 'min_db_user'
  - dbpwd: 'passwordyall'
  - dbname: 'mineralDB'

  tasks:
    - include: packages.yml
    # - include: user.yml
    - include: mysql.yml
    - include: deploy.yml
    - include: nginx.yml
